title: Kili Taylor
description: Welcome to my technical writing portfolio

url: "https://gentle-rain-docs.github.io"
baseurl: "/technical-writing-portfoilo"

remote_theme: jekyll/minima

markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-seo-tag
