title: Kili Taylor
description: Welcome to my technical writing portfolio!
url: "https://gentle-rain-docs.github.io"
baseurl: "/technical-writing-portfoilo"

author:
  name: Kili Taylor
  email: kili.taylor@protonmail.com

remote_theme: patdryburgh/hitchens

sass:
  style: compressed

markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

permalink: /:title/

nav:
  - title: Home
    url: /
  - title: Writing Samples
    url: /writing-samples/
  - title: Resume
    url: /resume/
  - title: About
    url: /about/

social:
  github: https://github.com/gentle-rain-docs
  linkedin: https://linkedin.com/in/kilitaylor

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post